apiVersion: apps/v1
kind: Deployment
metadata:
  name: ijkh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ijkh
  template:
    metadata:
      labels:
        app: ijkh
    spec:
      containers:
      - image: okteto.dev/ijkh:latest
        name: ijkh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/MeetApril-html.zip"
        - name: Vless_UUID
          value: "00ad636f-152f-446b-8d4d-1c9c6c19bda5"
        - name: Vless_Path
          value: "/00ad636f-152f-446b-8d4d-1c9c6c19bda5-vless"
        - name: Vmess_UUID
          value: "00ad636f-152f-446b-8d4d-1c9c6c19bda5"
        - name: Vmess_Path
          value: "/00ad636f-152f-446b-8d4d-1c9c6c19bda5-vmess"
        - name: Share_Path
          value: "/vpk"
